# Base configuration for Algo-Trading
# This file contains common settings used across all modes

app:
  name: "Algo-Trading"
  version: "0.1.0"
  description: "Fast crypto trading bot with LLM-powered decision making"

trading:
  default_symbols: ["BTC/USD", "ETH/USD"]
  bar_interval: "1m"
  market_order_timeout_seconds: 30
  limit_order_timeout_seconds: 300
  max_slippage_bps: 50  # 0.5%

risk:
  max_position_size: 0.1  # 10% of portfolio per symbol
  max_gross_exposure: 0.5  # 50% of portfolio
  max_daily_drawdown: 0.05  # 5% daily MDD
  drawdown_cooldown_minutes: 60
  per_trade_risk: 0.005  # 0.5% per trade
  circuit_breaker_spread_threshold: 0.01  # 1% spread stress

data:
  cache_retention_hours: 24
  feature_lookback_bars: 100
  alignment_tolerance_seconds: 5

llm:
  max_tokens: 2048
  temperature: 0.1
  max_retries: 3
  timeout_seconds: 30
  decision_cache_hours: 1

logging:
  level: "INFO"
  format: "json"
  retention_days: 14
  max_file_size_mb: 100
  backup_count: 5

performance:
  max_workers: 4
  queue_size: 1000
  heartbeat_interval_seconds: 30
