# Simulation broker configuration
# Used for backtesting and development

broker:
  type: "simulation"
  name: "SimBroker"
  
  # Simulation settings
  initial_capital: 100000  # USD
  commission_rate: 0.001   # 0.1%
  spread_bps: 10           # 0.1% spread
  slippage_model: "fixed"
  slippage_bps: 5          # 0.05% slippage
  
  # Market data simulation
  data_source: "historical"
  tick_size: 0.01          # Minimum price increment
  lot_size: 0.001          # Minimum quantity increment
  
  # Risk limits (simulation only)
  max_order_size: 10000    # USD
  max_daily_trades: 1000
  max_open_positions: 10
  
  # Latency simulation
  order_latency_ms: 50
  data_latency_ms: 10
  
  # Features
  supports_market_orders: true
  supports_limit_orders: true
  supports_stop_orders: true
  supports_margin: false
  supports_shorting: false
