# Data History Configuration
# This file defines the data collection windows, symbols, and paths for historical data

# Trading symbols to collect data for
symbols:
  - "BTCUSDT"
  - "ETHUSDT"

# Data frequency and format
timeframe: "1m"
data_format: "csv"  # For raw data storage

# Directory paths
raw_dir: "data/raw/binance"
processed_dir: "data/processed/binance"
features_dir: "data/features"

# Historical data collection windows (UTC)
history:
  start_ts_utc: "2024-07-01T00:00:00Z"
  end_ts_utc: "2025-08-20T23:59:00Z"

# Holdout period for testing (UTC)
holdout:
  start_ts_utc: "2025-07-01T00:00:00Z"
  end_ts_utc: "2025-08-20T23:59:00Z"

# Data source priorities
sources:
  primary: "binance:dump"      # CSV bulk downloads
  secondary: "binance:rest"    # REST API top-up

# Collection settings
collection:
  csv_download_parallel: 3     # Parallel CSV downloads
  rest_batch_size: 1000        # Max candles per REST request
  rest_rate_limit_ms: 100      # Rate limiting between REST calls
  gap_fill_threshold_hours: 24 # Fill gaps larger than this

# Quality control settings
quality:
  min_coverage_pct: 99.9
  max_duplicates: 0
  require_monotonic_ts: true
  validate_price_ranges: true
  validate_volume_ranges: true
