# Feature Engineering Configuration
# Professional-grade feature definitions for 1-minute crypto data

# Rolling window parameters (in minutes)
rolling_windows:
  ma: [20, 50, 100]
  ema: [20, 50]
  zscore: [20]
  volatility: [20, 50]
  regression: [20, 240, 720]
  volume: [20, 50]
  rsi: [14]
  atr: [14]

# Thresholds for feature calculations
thresholds:
  volume_spike_multiplier: 2.0
  volatility_regime_percentile: 0.80
  breakout_lookback: 20
  stop_atr_multiplier: 2.0
  intraday_reversal_threshold: 0.01
  winsorization_limits: [0.01, 0.99]

# Cross-asset relationships
cross_assets:
  driver_symbol: "BTCUSDT"
  pairs: ["ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT", "ADAUSDT", "DOGEUSDT", "AVAXUSDT", "TRXUSDT", "DOTUSDT"]

# Output configuration
output:
  path: "data/features/combined_features_1m.parquet"
  partition_by: ["symbol", "date"]
  compression: "snappy"

# Quality control parameters
qc:
  min_non_na_percentage: 0.95
  min_periods_required: true
  check_monotonic_timestamps: true
  check_unique_symbol_timestamp: true
  validate_feature_ranges: true

# Feature families to compute
feature_families:
  - "price_returns"      # Core price and return features
  - "trend_momentum"     # Trend and momentum indicators
  - "mean_reversion"     # Mean reversion signals
  - "volatility_risk"    # Volatility and risk metrics
  - "volume_liquidity"   # Volume and liquidity features
  - "cross_asset"        # Cross-asset relationships
  - "microstructure"     # Microstructure proxies
  - "regime"             # Market regime classification
  - "risk_execution"     # Risk and execution helpers
