# Default risk management configuration
# Defines risk limits, monitoring, and circuit breakers

risk:
  name: "DefaultRiskManager"
  version: "1.0.0"
  description: "Comprehensive risk management with multiple layers"
  
  # Portfolio-level limits
  portfolio:
    max_gross_exposure: 0.5      # 50% of portfolio
    max_net_exposure: 0.3        # 30% of portfolio
    max_cash_reserve: 0.2        # 20% cash reserve
    min_cash_reserve: 0.1        # 10% minimum cash
    
  # Position-level limits
  position:
    max_size_per_symbol: 0.1     # 10% per symbol
    max_size_per_sector: 0.2     # 20% per sector
    min_position_size: 0.01      # 1% minimum position
    max_correlation: 0.7         # Maximum correlation between positions
    
  # Risk metrics
  metrics:
    max_daily_var: 0.02          # 2% daily Value at Risk
    max_weekly_var: 0.05         # 5% weekly Value at Risk
    max_drawdown: 0.15           # 15% maximum drawdown
    max_daily_loss: 0.05         # 5% daily loss limit
    max_weekly_loss: 0.10        # 10% weekly loss limit
    
  # Circuit breakers
  circuit_breakers:
    daily_loss_threshold: 0.03   # 3% daily loss triggers circuit breaker
    drawdown_threshold: 0.10     # 10% drawdown triggers circuit breaker
    volatility_threshold: 0.05   # 5% volatility triggers circuit breaker
    spread_stress_threshold: 0.02 # 2% spread stress triggers circuit breaker
    
  # Circuit breaker actions
  actions:
    daily_loss:
      - "reduce_position_sizes"
      - "increase_stop_losses"
      - "pause_new_positions"
      - "cooldown_minutes": 60
      
    drawdown:
      - "flatten_positions"
      - "increase_cash_reserve"
      - "pause_trading"
      - "cooldown_minutes": 120
      
    volatility:
      - "reduce_leverage"
      - "tighten_stops"
      - "cooldown_minutes": 30
      
    spread_stress:
      - "switch_to_limit_orders"
      - "reduce_trade_frequency"
      - "cooldown_minutes": 15
      
  # Monitoring intervals
  monitoring:
    position_check_seconds: 5
    portfolio_check_seconds: 30
    risk_metrics_check_minutes: 5
    circuit_breaker_check_seconds: 10
    
  # Alerts and notifications
  alerts:
    enabled: true
    channels: ["log", "email", "slack"]
    thresholds:
      position_limit: 0.8        # Alert at 80% of limit
      portfolio_limit: 0.8       # Alert at 80% of limit
      drawdown: 0.05             # Alert at 5% drawdown
      daily_loss: 0.02           # Alert at 2% daily loss
