# Default trading strategy configuration
# Defines the base strategy parameters and features

strategy:
  name: "DefaultStrategy"
  version: "1.0.0"
  description: "Mean reversion with momentum confirmation"
  
  # Core parameters
  lookback_period: 100      # Number of bars to analyze
  rebalance_interval: "1m"  # How often to rebalance
  max_positions: 5          # Maximum concurrent positions
  
  # Entry conditions
  entry:
    momentum_threshold: 0.02    # 2% momentum required
    volatility_threshold: 0.01  # 1% volatility minimum
    volume_threshold: 1000      # Minimum volume in USD
    trend_confirmation_bars: 3  # Bars to confirm trend
    
  # Exit conditions
  exit:
    profit_target: 0.05         # 5% profit target
    stop_loss: 0.03             # 3% stop loss
    max_hold_time_hours: 24     # Maximum position hold time
    trailing_stop: true
    trailing_stop_distance: 0.02  # 2% trailing stop
    
  # Position sizing
  sizing:
    method: "kelly_criterion"   # kelly_criterion, fixed, volatility
    base_size: 0.02            # 2% base position size
    max_size: 0.1              # 10% maximum position size
    volatility_adjustment: true
    
  # Feature engineering
  features:
    technical_indicators:
      - "sma_20"
      - "sma_50"
      - "rsi_14"
      - "macd"
      - "bollinger_bands"
      - "atr_14"
    
    price_features:
      - "returns_1m"
      - "returns_5m"
      - "returns_15m"
      - "volatility_rolling"
      - "price_momentum"
      
    volume_features:
      - "volume_sma_20"
      - "volume_ratio"
      - "vwap"
      
  # Risk management
  risk:
    max_correlation: 0.7        # Maximum correlation between positions
    sector_exposure_limit: 0.3  # Maximum exposure to any sector
    drawdown_cut: 0.05          # Cut positions at 5% drawdown
    
  # Performance targets
  targets:
    min_sharpe_ratio: 1.0
    max_drawdown: 0.15
    min_win_rate: 0.55
    max_turnover: 2.0
